use serde::Serialize;
use std::{fs, io::Write, path::{Path, PathBuf}, process::Command};
use walkdir::WalkDir;

#[derive(Serialize)] struct PlatformInfo { os: String, arch: String, kdev_root: String }
#[derive(Serialize)] struct LinuxEnvironment { available: bool, provider: String, detail: String }

fn kdev_root() -> Result<PathBuf, String> { let exe=std::env::current_exe().map_err(|e|format!("cannot locate KDev executable: {e}"))?; exe.parent().map(Path::to_path_buf).ok_or_else(||"cannot determine KDev root".into()) }
fn safe_workspace_path(relative_path:&str)->Result<PathBuf,String>{let root=kdev_root()?;let p=Path::new(relative_path);if p.is_absolute(){return Err("absolute workspace paths are not allowed".into())}if p.components().any(|c|matches!(c,std::path::Component::ParentDir)){return Err("parent-directory traversal is not allowed".into())}Ok(root.join(p))}
fn safe_project_name(name:&str)->Result<String,String>{let n=name.trim();if n.is_empty()||n.len()>80{return Err("project name must be 1-80 characters".into())}if n=="."||n==".."||n.chars().any(|c|c=='/'||c=='\\'||c.is_control()){return Err("invalid project name".into())}Ok(n.to_string())}
#[cfg(windows)] fn wsl_distros()->Vec<String>{Command::new("wsl.exe").args(["-l","-q"]).output().ok().map(|o|String::from_utf8_lossy(&o.stdout).lines().map(str::trim).filter(|s|!s.is_empty()).map(String::from).collect()).unwrap_or_default()}
#[cfg(windows)] fn preferred_wsl_distro()->Option<String>{let d=wsl_distros();d.iter().find(|x|x.to_lowercase().contains("kali")).cloned().or_else(||d.first().cloned())}
#[tauri::command] fn platform_info()->Result<PlatformInfo,String>{Ok(PlatformInfo{os:std::env::consts::OS.into(),arch:std::env::consts::ARCH.into(),kdev_root:kdev_root()?.display().to_string()})}
#[tauri::command] fn linux_environment()->Result<LinuxEnvironment,String>{#[cfg(target_os="windows")]{let d=wsl_distros();if let Some(k)=d.iter().find(|x|x.to_lowercase().contains("kali")){return Ok(LinuxEnvironment{available:true,provider:format!("WSL2 / {k}"),detail:format!("Kali Linux distribution detected: {k}")})}if !d.is_empty(){return Ok(LinuxEnvironment{available:true,provider:"WSL2".into(),detail:format!("Linux distribution detected: {}. Install Kali separately if you want the Kali environment.",d.join(", "))})}let s=Command::new("wsl.exe").args(["--status"]).output();return Ok(LinuxEnvironment{available:false,provider:"WSL2".into(),detail:if s.map(|o|o.status.success()).unwrap_or(false){"WSL is installed, but no Linux distribution is registered.".into()}else{"WSL2 is not available on this host. The Linux workspace UI remains available.".into()}})}#[cfg(not(target_os="windows"))]{let shell=std::env::var("SHELL").unwrap_or_else(|_|"/bin/bash".into());let a=Path::new(&shell).exists()||Path::new("/bin/bash").exists();Ok(LinuxEnvironment{available:a,provider:"native shell".into(),detail:if a{format!("Shell detected: {shell}")}else{"No compatible shell was detected.".into()}})}}
#[tauri::command] fn run_linux_command(command:String,working_directory:Option<String>)->Result<String,String>{let c=command.trim();if c.is_empty(){return Ok(String::new())}if c.len()>4096{return Err("command is too long".into())}let cwd=working_directory.map(|p|safe_workspace_path(&p)).transpose()?;#[cfg(target_os="windows")]let output={let d=preferred_wsl_distro().ok_or_else(||"No WSL Linux distribution is installed.".to_string())?;let mut x=Command::new("wsl.exe");x.args(["-d",&d,"--","bash","-lc",c]);if let Some(dir)=cwd{x.current_dir(dir);}x.output().map_err(|e|format!("failed to start Linux shell: {e}"))?};#[cfg(not(target_os="windows"))]let output={let mut x=Command::new("bash");x.args(["-lc",c]);if let Some(dir)=cwd{x.current_dir(dir);}x.output().map_err(|e|format!("failed to start bash: {e}"))?};let mut t=String::from_utf8_lossy(&output.stdout).to_string();let e=String::from_utf8_lossy(&output.stderr);if !e.is_empty(){t.push_str(&e)}if !output.status.success()&&t.trim().is_empty(){t=format!("command exited with status {}",output.status)}Ok(t)}
#[tauri::command] fn create_project(name:String,template:String)->Result<Vec<String>,String>{let name=safe_project_name(&name)?;let root=kdev_root()?.join("workspace/projects").join(&name);if root.exists(){return Err(format!("project '{name}' already exists"))}fs::create_dir_all(&root).map_err(|e|format!("cannot create project: {e}"))?;let files:Vec<(&str,&str)>=match template.as_str(){"python"=>vec![("main.py","def main():\n    print(\"Hello from KDev\")\n\nif __name__ == \"__main__\":\n    main()\n"),("README.md","# KDev Python Project\n")],"web"=>vec![("index.html","<!doctype html>\n<html><head><meta charset=\"utf-8\"><title>KDev</title><link rel=\"stylesheet\" href=\"style.css\"></head><body><main><h1>Hello from KDev</h1><p>Your portable web project is ready.</p></main><script src=\"app.js\"></script></body></html>\n"),("style.css","body { font-family: system-ui, sans-serif; margin: 3rem; }\n"),("app.js","console.log(\"KDev web project ready\");\n"),("README.md","# KDev Web Project\n")],"react"=>vec![("package.json","{\n  \"name\": \"kdev-react-app\",\n  \"private\": true,\n  \"type\": \"module\",\n  \"scripts\": {\"dev\": \"vite\", \"build\": \"vite build\"},\n  \"dependencies\": {\"vite\": \"latest\",\"react\": \"latest\",\"react-dom\": \"latest\"}\n}\n"),("index.html","<div id=\"root\"></div><script type=\"module\" src=\"/src/main.jsx\"></script>\n"),("src/main.jsx","import React from 'react';\nimport { createRoot } from 'react-dom/client';\nfunction App(){ return <h1>KDev React Project</h1>; }\ncreateRoot(document.getElementById('root')).render(<App />);\n")],"next"=>vec![("package.json","{\n  \"name\": \"kdev-next-app\",\n  \"private\": true,\n  \"scripts\": {\"dev\": \"next dev\", \"build\": \"next build\", \"start\": \"next start\"},\n  \"dependencies\": {\"next\": \"latest\",\"react\": \"latest\",\"react-dom\": \"latest\"}\n}\n"),("app/page.jsx","export default function Page(){ return <main><h1>KDev Next.js Project</h1></main>; }\n"),("app/layout.jsx","export default function Layout({children}){ return <html><body>{children}</body></html>; }\n")],"typescript"=>vec![("main.ts","const message: string = 'Hello from KDev TypeScript';\nconsole.log(message);\n")],_=>vec![("README.md","# KDev Project\n\nCreated with KDev.\n")]};let mut created=Vec::new();for(relative,content)in files{let path=root.join(relative);if let Some(parent)=path.parent(){fs::create_dir_all(parent).map_err(|e|e.to_string())?}let mut f=fs::File::create(&path).map_err(|e|format!("cannot create {relative}: {e}"))?;f.write_all(content.as_bytes()).map_err(|e|e.to_string())?;f.sync_all().map_err(|e|e.to_string())?;created.push(format!("workspace/projects/{name}/{relative}"))}Ok(created)}
#[tauri::command] fn create_workspace_file(relative_path:String,content:String)->Result<(),String>{let p=safe_workspace_path(&relative_path)?;if p.exists(){return Err("file already exists".into())}if let Some(parent)=p.parent(){fs::create_dir_all(parent).map_err(|e|e.to_string())?}fs::write(p,content).map_err(|e|e.to_string())}
#[tauri::command] fn delete_workspace_file(relative_path:String)->Result<(),String>{let p=safe_workspace_path(&relative_path)?;if !p.exists()||!p.is_file(){return Err("file not found".into())}fs::remove_file(p).map_err(|e|e.to_string())}
#[tauri::command] fn write_workspace_file(relative_path:String,content:String)->Result<(),String>{let p=safe_workspace_path(&relative_path)?;if let Some(parent)=p.parent(){fs::create_dir_all(parent).map_err(|e|e.to_string())?}let tmp=p.with_extension(format!("kdev-tmp-{}",std::process::id()));{let mut f=fs::File::create(&tmp).map_err(|e|e.to_string())?;f.write_all(content.as_bytes()).map_err(|e|e.to_string())?;f.sync_all().map_err(|e|e.to_string())?}#[cfg(windows)]if p.exists(){fs::remove_file(&p).map_err(|e|e.to_string())?}fs::rename(tmp,p).map_err(|e|e.to_string())}
#[tauri::command] fn read_workspace_file(relative_path:String)->Result<String,String>{fs::read_to_string(safe_workspace_path(&relative_path)?).map_err(|e|e.to_string())}
#[tauri::command] fn list_workspace_files()->Result<Vec<String>,String>{let k=kdev_root()?;let root=k.join("workspace");if !root.exists(){return Ok(Vec::new())}let mut v=Vec::new();for e in WalkDir::new(root).into_iter().filter_map(Result::ok){if e.file_type().is_file(){if let Ok(p)=e.path().strip_prefix(&k){v.push(p.to_string_lossy().replace('\\',"/"))}}}v.sort();Ok(v)}
#[tauri::command] fn list_projects()->Result<Vec<String>,String>{let root=kdev_root()?.join("workspace/projects");if !root.exists(){return Ok(Vec::new())}let mut v=Vec::new();for e in fs::read_dir(root).map_err(|e|e.to_string())?.filter_map(Result::ok){if e.file_type().map(|t|t.is_dir()).unwrap_or(false){if let Some(n)=e.file_name().to_str(){v.push(n.to_string())}}}v.sort();Ok(v)}
#[cfg_attr(mobile,tauri::mobile_entry_point)]pub fn run(){tauri::Builder::default().invoke_handler(tauri::generate_handler![platform_info,linux_environment,run_linux_command,create_project,create_workspace_file,delete_workspace_file,write_workspace_file,read_workspace_file,list_workspace_files,list_projects]).run(tauri::generate_context!()).expect("error while running KDev");}
